### ISSUE TITLE
[Issue]: Ecosystem and Partners more link ends in 404

### ISSUE THREAD

**Issue by Element115sw** [ROCm/rocm-blogs#21]
### Problem Description

https://rocm.blogs.amd.com/blog/category/ecosystem-and-partners.html

### Operating System

seems silly for the blog issue report

### CPU

seems silly for the blog issue report

### GPU

seems silly for the blog issue report

### ROCm Version

seems silly for the blog issue report

### Output of /opt/rocm/bin/rocminfo --support

seems silly for the blog issue report

**Comment by saadrahim** [comment]
Thanks for reporting the problem. I've fixed the broken link.
